simplify html files
CMDM-Lab/CMDM-Lab.github.io pull request #69
Opened 2021-05-06 02:49 UTC by yuyuan871111

Simplify the html files in order to make the website more easily be maintained.

2021-05-06 15:22 UTC, hsiaoyi0504 commented on contents/member_zh.html
>  						<h4><b>黃立緯 (Li-Wei Huang)</b></h4>
Li-Wei是行政助理

2021-05-06 15:23 UTC, hsiaoyi0504 commented on contents/member_zh.html
> +					<h4><b>謝秉翰 (Bing-Han Hsieh)</b></h4>
秉翰已畢業

2021-05-06 15:23 UTC, hsiaoyi0504 commented on contents/member_zh.html
> +					<h4><b>張家瑜 (Chia Yu Chang)</b></h4>
家瑜已畢業

2021-05-06 15:23 UTC, hsiaoyi0504 requested changes
稍微review了一下

2021-05-11 11:39 UTC, yuyuan871111 commented
我再重新改了一下實驗室網站的運作架構，用?content=的Flag去跳轉頁面。同時根據天爵學長給的實驗室通訊錄更新了實驗室成員、畢業成員，footer也有做年份的更新。

2021-05-11 14:25 UTC, merged